version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - microservice1
      - microservice2
    networks:
      - my_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  microservice1:
    image: microservice1:latest
    networks:
      - my_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  microservice2:
    image: microservice2:latest
    networks:
      - my_network
    depends_on:
      - microservice1
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  my_network:
    driver: overlay
    attachable: true
